name: Generate Blogs JSON

on:
  push:
    paths:
      - "blogs/**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate blogs.json
        run: |
          echo "[" > blogs.json
          first=true

          # Loop through each Markdown file inside blogs/*/
          for file in blogs/*/*.md; do
            folder=$(basename "$(dirname "$file")")   # folder name = blog title
            filename=$(basename "$file")             # file name = blog.md
            title="$folder"                          # use folder name as title
            date=$(git log -1 --format="%ad" --date=short -- "$file")

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> blogs.json
            fi

            echo "  {\"file\": \"$filename\", \"title\": \"$title\", \"date\": \"$date\"}" >> blogs.json
          done

          echo "]" >> blogs.json

      - name: Commit and push blogs.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add blogs.json
          git commit -m "Update blogs.json" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
