
name: Generate Blogs JSON

on:
  push:
    paths:
      - "blogs/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate blogs.json
        run: |
          echo "[" > blogs.json
          first=true
          for file in blogs/*.md; do
            title=$(head -n 1 "$file" | sed 's/^# //')
            date=$(git log -1 --format="%ad" --date=short -- "$file")
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> blogs.json
            fi
            echo "  {\"file\": \"$(basename $file)\", \"title\": \"$title\", \"date\": \"$date\"}" >> blogs.json
          done
          echo "]" >> blogs.json
      - name: Commit and push blogs.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add blogs.json
          git commit -m "Update blogs.json" || echo "No changes"
          git push

