name: Generate Blogs JSON

on:
  push:
    paths:
      - "blogs/*.md"

permissions:
  contents: write   # 👈 give write access to GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false   # 👈 disable default credentials
          fetch-depth: 0               # needed for git log

      - name: Generate blogs.json
        run: |
          echo "[" > blogs.json
          first=true
          for file in blogs/*.md; do
            title=$(head -n 1 "$file" | sed 's/^# //')
            date=$(git log -1 --format="%ad" --date=short -- "$file")
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> blogs.json
            fi
            echo "  {\"file\": \"$(basename $file)\", \"title\": \"$title\", \"date\": \"$date\"}" >> blogs.json
          done
          echo "]" >> blogs.json

      - name: Commit and push blogs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blogs.json
          git commit -m "Update blogs.json" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
